const CARDS = {
	"C1": [1, 9,"res://Scripts/cardsconsumes/Manzana.gd"],
	"C2": [0, 11,"res://Scripts/cardsconsumes/Platano.gd"],
	"C3": [1, 9,"res://Scripts/cardsconsumes/Libro.gd"],
	"C4": [3, 9,"res://Scripts/cardsconsumes/Mascara.gd"],
	"C5": [0, 9, "res://Scripts/cardsconsumes/Cactus.gd"],
	"C6": [2, 9, "res://Scripts/cardsconsumes/Diana.gd"],
	"C7": [2, 9, "res://Scripts/cardsconsumes/Arbusto.gd"],
	"C8": [0, 9, "res://Scripts/cardsconsumes/Caja_misteriosa.gd"],
	"R1": [1, 4,"res://Scripts/cardsconsumes/manzana_dorada.gd"],
	"R2": [2, 4,"res://Scripts/cardsconsumes/TNT.gd"],
	"R3": [2, 4, "res://Scripts/cardsconsumes/Durum.gd"],
	"R4": [1, 4, "res://Scripts/cardsconsumes/Pan.gd"],
	"R5": [1, 4, "res://Scripts/cardsconsumes/Ojo.gd"],
	"R6": [1, 4, "res://Scripts/cardsconsumes/Oak.gd"],
	"E1": [2, 1,"res://Scripts/cardsconsumes/Monster.gd"],
	"E2": [1, 1,"res://Scripts/cardsconsumes/Ruleta.gd"],
}
